/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Ole Gunnar Isager (https://sketchfab.com/FrenchBaguette)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cookie-school-project-434b04afb75d4525ae5eb272282d736d
Title: Cookie (School Project)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export default function Cookie(props) {
  const { nodes, materials } = useGLTF("./assets/cookie/scene-transformed.glb");
  return (
    <Canvas camera={{}}>
      <OrbitControls />

      <ambientLight intensity={1} />

      <group scale={100} {...props} dispose={null}>
        <mesh
          geometry={nodes.pCylinder15_lambert12_0.geometry}
          material={materials.lambert12}
        />
      </group>
    </Canvas>
  );
}

useGLTF.preload("./assets/cookie/scene-transformed.glb");
