/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Designed By Jonathan (https://sketchfab.com/designedbyjonathan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-cookies-6f2ef02ceb334990a867c1437f4a65cd
Title: Low Poly Cookies
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export default function Cookies(props) {
  const { nodes, materials } = useGLTF(
    "./assets/cookies/scene-transformed.glb"
  );
  return (
    <Canvas
      camera={{
        position: [150, 100, 150],
      }}
    >
      <OrbitControls />
      
      <ambientLight intensity={1} />

      <group {...props} dispose={null}>
        <group scale={0.5}>
          <group
            position={[128.32, 33.94, -221.96]}
            rotation={[-1.31, -1.33, -1.08]}
          >
            <mesh
              geometry={nodes.Sphere_2_Mat1_1.geometry}
              material={materials["Mat.1"]}
            />
            <mesh
              geometry={nodes.Sphere_2_Mat_0.geometry}
              material={materials.material}
            />
          </group>
          <group position={[0, 32.14, -82.21]} rotation={[-0.12, 0, 0]}>
            <mesh
              geometry={nodes.Sphere_1_Mat1_1.geometry}
              material={materials["Mat.1"]}
            />
            <mesh
              geometry={nodes.Sphere_1_Mat1_0.geometry}
              material={materials["Mat.1_0"]}
            />
          </group>
          <group position={[0, 0, 18.18]} rotation={[Math.PI, 0.89, -Math.PI]}>
            <mesh
              geometry={nodes.Sphere_Mat1_1.geometry}
              material={materials["Mat.1"]}
            />
            <mesh
              geometry={nodes.Sphere_Mat2_0.geometry}
              material={materials["Mat.2"]}
            />
          </group>
        </group>
      </group>
    </Canvas>
  );
}

useGLTF.preload("./assets/cookies/scene-transformed.glb");
