/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: OHOW (https://sketchfab.com/OHOW)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hotdog-low-poly-food-g06-f1a16ce205724dfa8fb72ff397319f5e
Title: Hotdog Low Poly Food G06
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export default function Hotdog(props) {
  const { nodes, materials } = useGLTF("./assets/hotdog/scene-transformed.glb");
  return (
    <Canvas
      camera={{
        position: [150, 100, 150],
      }}
    >
      <OrbitControls autoRotate={true} />
      <ambientLight intensity={1} />
      <group scale={0.5} {...props} dispose={null}>
        <mesh
          geometry={nodes.Hotdog_Hotdog_0.geometry}
          material={materials.Hotdog}
        />
      </group>
    </Canvas>
  );
}

useGLTF.preload("./assets/hotdog/scene-transformed.glb");
