/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: kristenlee (https://sketchfab.com/kristenlee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/50s-diner-low-poly-b0f7d92279164a24997b110f02067bb3
Title: 50's Diner Low Poly
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import audio from "./elvis-presley-jailhouse-rock-music-video.mp3";
export default function Resto({ hideGroup }) {
  const { nodes, materials } = useGLTF("./assets/resto/scene-transformed.glb");
  const audioRef = useRef(null);

  const handleGroupClick = (event) => {
    console.log("Group Clicked");
    // You can access event properties like event.object or event.intersections here
    if (audioRef.current) {
      audioRef.current.play();
    }
  };

  return (
    <Canvas
      camera={{ position: [150, 100, 150] }}
      raycast={{ intersectObjects: [] }} // Enable raycasting
    >
      <OrbitControls
        minDistance={100}
        minPolarAngle={Math.PI / 4}
        maxPolarAngle={Math.PI / 2.5}
        maxDistance={200}
        enablePan={false}
        minAzimuthAngle={-Math.PI / 12} // Minimum azimuth angle (yaw)
        maxAzimuthAngle={Math.PI / 2} // Maximum azimuth angle (yaw)
      />
      <ambientLight intensity={1} />
      <group dispose={null}>
        <group onClick={handleGroupClick} scale={0.7}>
          {/* deze */}
          {hideGroup && (
            <group
              position={[77.08, 50.2, -22.26]}
              rotation={[Math.PI / 2, 0, -Math.PI]}
              scale={5.21}
            >
              <mesh
                geometry={nodes.Cylinder002_Material005_0.geometry}
                material={materials["Material.005"]}
              />
              <mesh
                geometry={nodes.Cylinder002_Material002_0.geometry}
                material={materials["Material.002"]}
              />
              <mesh
                geometry={nodes.Cylinder002_Material003_0.geometry}
                material={materials["Material.003"]}
              />
              <mesh
                geometry={nodes.Cylinder002_Material001_0.geometry}
                material={materials["Material.001"]}
              />
              <mesh
                geometry={nodes.Cylinder002_Material004_0.geometry}
                material={materials["Material.004"]}
              />
              <mesh
                geometry={nodes.Cylinder002_Material012_0.geometry}
                material={materials["Material.012"]}
              />
            </group>
          )}

          {/* deze */}
          {hideGroup && (
            <group
              position={[65.36, 55.26, -21.29]}
              rotation={[-Math.PI / 2, 0, 0.81]}
              scale={5.56}
            >
              <mesh
                geometry={nodes.Cylinder005_Material006_0.geometry}
                material={materials["Material.006"]}
              />
              <mesh
                geometry={nodes.Cylinder005_White_0.geometry}
                material={materials.White}
              />
            </group>
          )}

          <group
            position={[71.87, 52.44, -39.42]}
            rotation={[-1.59, 0.12, 2.57]}
            scale={[0, 3.83, 10.21]}
          >
            <mesh
              geometry={nodes.Plane004_Material010_0.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              geometry={nodes.Plane004_Material006_0.geometry}
              material={materials["Material.006"]}
            />
            <mesh
              geometry={nodes.Plane004_Material011_0.geometry}
              material={materials.White}
            />
          </group>
          <group
            position={[90.05, 15, -74.78]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={10.88}
          >
            <mesh
              geometry={nodes.Cube001_Material013_0.geometry}
              material={materials["Material.013"]}
            />
            <mesh
              geometry={nodes.Cube001_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group
            position={[76, 16.18, 7.18]}
            rotation={[-Math.PI / 2, 0, -1.64]}
            scale={[0.77, 0.77, 1.91]}
          >
            <mesh
              geometry={nodes.Cylinder003_Silver_0.geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Cylinder003_Red_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Cylinder003_Material007_0.geometry}
              material={materials.White}
            />
            <mesh
              geometry={nodes.Cylinder003_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group
            position={[69.8, 15, -74.78]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={10.88}
          >
            <mesh
              geometry={nodes.Cube002_Material_0.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Cube002_Material013_0.geometry}
              material={materials["Material.013"]}
            />
          </group>
          <group
            position={[49.41, 15, -74.78]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={10.88}
          >
            <mesh
              geometry={nodes.Cube004_Material013_0.geometry}
              material={materials["Material.013"]}
            />
            <mesh
              geometry={nodes.Cube004_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group
            position={[29.09, 15, -74.78]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={10.88}
          >
            <mesh
              geometry={nodes.Cube005_Material_0.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Cube005_Material013_0.geometry}
              material={materials["Material.013"]}
            />
          </group>
          <group
            position={[8.7, 15, -74.78]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={10.88}
          >
            <mesh
              geometry={nodes.Cube006_Material013_0.geometry}
              material={materials["Material.013"]}
            />
            <mesh
              geometry={nodes.Cube006_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group
            position={[-11.62, 15, -74.78]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={10.88}
          >
            <mesh
              geometry={nodes.Cube007_Material_0.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Cube007_Material013_0.geometry}
              material={materials["Material.013"]}
            />
          </group>
          <group
            position={[-32.01, 15, -74.78]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={10.88}
          >
            <mesh
              geometry={nodes.Cube008_Material013_0.geometry}
              material={materials["Material.013"]}
            />
            <mesh
              geometry={nodes.Cube008_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group
            position={[-52.33, 15, -74.78]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={10.88}
          >
            <mesh
              geometry={nodes.Cube009_Material_0.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Cube009_Material013_0.geometry}
              material={materials["Material.013"]}
            />
          </group>
          <group
            position={[-72.72, 15, -74.78]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={10.88}
          >
            <mesh
              geometry={nodes.Cube010_Material013_0.geometry}
              material={materials["Material.013"]}
            />
            <mesh
              geometry={nodes.Cube010_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group
            position={[72.53, 16.18, -60.19]}
            rotation={[-Math.PI / 2, 0, 1.91]}
            scale={[0.77, 0.77, 1.91]}
          >
            <mesh
              geometry={nodes.Cylinder001_Silver_0.geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Cylinder001_Red_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Cylinder001_Material007_0.geometry}
              material={materials.White}
            />
            <mesh
              geometry={nodes.Cylinder001_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group
            position={[74.17, 46.34, -27.29]}
            rotation={[-Math.PI / 2, 0, -3.09]}
            scale={86.8}
          >
            <mesh
              geometry={nodes.Vert002_Silver_0.geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Vert002_Material_0.geometry}
              material={materials.Material}
            />
          </group>

          <group
            position={[-37.1, 32.78, -32.34]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[18.53, 15.9, 15.9]}
          >
            <mesh
              geometry={nodes.Cube011_Material_0.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Cube011_Red_0.geometry}
              material={materials.material}
            />
          </group>
          <group
            position={[-31.6, 66.43, -47.32]}
            rotation={[-1.57, 0, 0]}
            scale={[18.53, 10.81, 15.9]}
          >
            <mesh
              geometry={nodes.Cube012_Red_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Cube012_Material013_0.geometry}
              material={materials["Material.013"]}
            />
          </group>
          <group
            position={[80.91, 16.18, 72.31]}
            rotation={[-Math.PI / 2, 0, -0.07]}
            scale={[0.77, 0.77, 1.91]}
          >
            <mesh
              geometry={nodes.Cylinder004_Silver_0.geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Cylinder004_Red_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Cylinder004_Material007_0.geometry}
              material={materials.White}
            />
            <mesh
              geometry={nodes.Cylinder004_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group
            position={[7.3, 16.18, 69.57]}
            rotation={[-Math.PI / 2, 0, -3.08]}
            scale={[0.77, 0.77, 1.91]}
          >
            <mesh
              geometry={nodes.Cylinder008_Silver_0.geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Cylinder008_Red_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Cylinder008_Material007_0.geometry}
              material={materials.White}
            />
            <mesh
              geometry={nodes.Cylinder008_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group
            position={[46.44, 45.51, 74.15]}
            rotation={[-Math.PI / 2, 0, -1.52]}
            scale={86.8}
          >
            <mesh
              geometry={nodes.Vert001_Silver_0.geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Vert001_Material_0.geometry}
              material={materials.Material}
            />
          </group>

          <group
            position={[-74.95, 17.37, 77.22]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[2.27, 2.27, 3.49]}
          >
            <mesh
              geometry={nodes.Cylinder_Silver_0.geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Cylinder_Material014_0.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cylinder_Red_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Cylinder_JukeboxGreen_0.geometry}
              material={materials.JukeboxGreen}
            />
            <mesh
              geometry={nodes.Cylinder_JukeboxPink_0.geometry}
              material={materials.JukeboxPink}
            />
            <mesh
              geometry={nodes.Cylinder_JukeboxYellow_0.geometry}
              material={materials.JukeboxYellow}
            />
            <mesh
              geometry={nodes.Cylinder_Silver001_0.geometry}
              material={materials["Silver.001"]}
            />
            <mesh
              geometry={nodes.Cylinder_Material003_0.geometry}
              material={materials["Material.003"]}
            />
            <mesh
              geometry={nodes.Cylinder_Glass_0.geometry}
              material={materials.Glass}
            />
          </group>
          <group
            position={[-37.1, 32.78, -32.34]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[18.53, 15.9, 15.9]}
          >
            <mesh
              geometry={nodes.Cube003_Material_0.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Cube003_Red_0.geometry}
              material={materials.material}
            />
          </group>

          <group
            position={[-31.6, 109.62, 15.54]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[8.7, 14.76, 8.7]}
          >
            <mesh
              geometry={nodes.Plane_Material_0.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Plane_Red_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Plane_Material013_0.geometry}
              material={materials["Material.013"]}
            />
          </group>
          {hideGroup && (
            <group
              position={[61.25, 48.87, 77.64]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[-4.9, 4.9, 3.9]}
            >
              <mesh
                geometry={nodes.Circle_Glass001_0.geometry}
                material={materials["Glass.001"]}
              />
              <mesh
                geometry={nodes.Circle_Ice_Cream_0.geometry}
                material={materials.Ice_Cream}
              />
              <mesh
                geometry={nodes.Circle_Red_0.geometry}
                material={materials.material}
              />
              <mesh
                geometry={nodes.Circle_Green_0.geometry}
                material={materials.Green}
              />
              <mesh
                geometry={nodes.Circle_Material_0.geometry}
                material={materials.Material}
              />
            </group>
          )}
          <group position={[21.54, 96.09, -85.34]} scale={49.97}>
            <mesh
              geometry={nodes.Text001_Material027_0.geometry}
              material={materials["Material.027"]}
            />
            <mesh
              geometry={nodes.Text001_Red_0.geometry}
              material={materials.material}
            />
          </group>
          {hideGroup && (
            <group
              position={[72.62, 49.81, -26.96]}
              rotation={[-Math.PI / 2, 0, -0.22]}
              scale={[11.99, 14.36, 15.63]}
            >
              <mesh
                geometry={nodes.Plane002_Material022_0.geometry}
                material={materials["Material.022"]}
              />
              <mesh
                geometry={nodes.Plane002_Material023_0.geometry}
                material={materials.White}
              />
            </group>
          )}

          {/* deze */}
          {hideGroup && (
            <group
              position={[38.11, 49.79, 76.69]}
              rotation={[Math.PI / 2, 0, 2.44]}
              scale={5.21}
            >
              <mesh
                geometry={nodes.Cylinder009_Material005_0.geometry}
                material={materials["Material.005"]}
              />
              <mesh
                geometry={nodes.Cylinder009_Material002_0.geometry}
                material={materials["Material.002"]}
              />
              <mesh
                geometry={nodes.Cylinder009_Material003_0.geometry}
                material={materials["Material.003"]}
              />
              <mesh
                geometry={nodes.Cylinder009_Material001_0.geometry}
                material={materials["Material.001"]}
              />
              <mesh
                geometry={nodes.Cylinder009_Material004_0.geometry}
                material={materials["Material.004"]}
              />
              <mesh
                geometry={nodes.Cylinder009_Material012_0.geometry}
                material={materials["Material.012"]}
              />
            </group>
          )}
          {hideGroup && (
            <group
              position={[38.76, 48.79, 65.26]}
              rotation={[Math.PI / 2, 0, 2.83]}
              scale={[-4.9, 4.9, 3.9]}
            >
              <mesh
                geometry={nodes.Circle001_Glass001_0.geometry}
                material={materials["Glass.001"]}
              />
              <mesh
                geometry={nodes.Circle001_Ice_Cream001_0.geometry}
                material={materials["Ice_Cream.001"]}
              />
              <mesh
                geometry={nodes.Circle001_Green_0.geometry}
                material={materials.Green}
              />
              <mesh
                geometry={nodes.Circle001_Red_0.geometry}
                material={materials.material}
              />
              <mesh
                geometry={nodes.Circle001_Material_0.geometry}
                material={materials.Material}
              />
            </group>
          )}

          <group
            position={[-76.07, 70.5, 35.21]}
            rotation={[-Math.PI / 2, 0, 1.3]}
            scale={2.08}
          >
            <mesh
              geometry={nodes.Circle010_Silver001_0.geometry}
              material={materials["Silver.001"]}
            />
            <mesh
              geometry={nodes.Circle010_Red_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Circle010_Material_0.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Circle010_Material013_0.geometry}
              material={materials["Material.013"]}
            />
          </group>
          <group
            position={[-77.06, 78.86, -62.3]}
            rotation={[-Math.PI / 2, 0, 1.11]}
            scale={3.17}
          >
            <mesh
              geometry={nodes.Cylinder011_Material006_0.geometry}
              material={materials["Material.006"]}
            />
            <mesh
              geometry={nodes.Cylinder011_White_0.geometry}
              material={materials.White}
            />
          </group>

          {hideGroup && (
            <group
              position={[-82.08, 78.86, -59.81]}
              rotation={[-Math.PI / 2, 0, 1.11]}
              scale={3.17}
            >
              <mesh
                geometry={nodes.Cylinder012_Material006_0.geometry}
                material={materials["Material.006"]}
              />
              <mesh
                geometry={nodes.Cylinder012_White_0.geometry}
                material={materials.White}
              />
            </group>
          )}
          {hideGroup && (
            <group
              position={[-32.11, 68.34, -17.13]}
              rotation={[-Math.PI / 2, 0, 3.05]}
              scale={[11.99, 14.36, 15.63]}
            >
              <mesh
                geometry={nodes.Plane007_Material022_0.geometry}
                material={materials["Material.022"]}
              />
              <mesh
                geometry={nodes.Plane007_Material023_0.geometry}
                material={materials.White}
              />
            </group>
          )}
          {hideGroup && (
            <group
              position={[-30.52, 68.86, -23.53]}
              rotation={[Math.PI / 2, 0, 0.26]}
              scale={5.21}
            >
              <mesh
                geometry={nodes.Cylinder021_Material005_0.geometry}
                material={materials["Material.005"]}
              />
              <mesh
                geometry={nodes.Cylinder021_Material002_0.geometry}
                material={materials["Material.002"]}
              />
              <mesh
                geometry={nodes.Cylinder021_Material003_0.geometry}
                material={materials["Material.003"]}
              />
              <mesh
                geometry={nodes.Cylinder021_Material001_0.geometry}
                material={materials["Material.001"]}
              />
              <mesh
                geometry={nodes.Cylinder021_Material004_0.geometry}
                material={materials["Material.004"]}
              />
              <mesh
                geometry={nodes.Cylinder021_Material012_0.geometry}
                material={materials["Material.012"]}
              />
            </group>
          )}
          {hideGroup && (
            <group
              position={[-35.53, 70.5, -14.51]}
              rotation={[-1.67, 0.06, -2.8]}
              scale={[0, 3.83, 10.21]}
            >
              <mesh
                geometry={nodes.Plane010_Material010_0.geometry}
                material={materials["Material.010"]}
              />
              <mesh
                geometry={nodes.Plane010_Material006_0.geometry}
                material={materials["Material.006"]}
              />
              <mesh
                geometry={nodes.Plane010_Material011_0.geometry}
                material={materials.White}
              />
            </group>
          )}

          <group position={[-52.49, 118.42, -86.57]} scale={[7.43, 4.93, 6.53]}>
            <mesh
              geometry={nodes.Plane011_Cherry_0.geometry}
              material={materials.Cherry}
            />
            <mesh
              geometry={nodes.Plane011_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group position={[-52.49, 106.21, -86.57]} scale={[7.43, 4.93, 6.53]}>
            <mesh
              geometry={nodes.Plane012_Yellow_0.geometry}
              material={materials.Yellow}
            />
            <mesh
              geometry={nodes.Plane012_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group position={[-52.49, 93.44, -86.57]} scale={[7.43, 4.93, 6.53]}>
            <mesh
              geometry={nodes.Plane013_Material027_0.geometry}
              material={materials["Material.027"]}
            />
            <mesh
              geometry={nodes.Plane013_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group
            position={[6.16, 66.43, -70.75]}
            rotation={[-1.57, 0, 0]}
            scale={[18.53, 10.81, 15.9]}
          >
            <mesh
              geometry={nodes.Cube017_Red_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Cube017_Material013_0.geometry}
              material={materials["Material.013"]}
            />
          </group>

          <group
            position={[-24.25, 68.38, -74.61]}
            rotation={[-Math.PI / 2, 0, 0.86]}
            scale={2.9}
          >
            <mesh
              geometry={nodes.Circle003_Material_0.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Circle003_Material013_0.geometry}
              material={materials["Material.013"]}
            />
          </group>
          <group
            position={[-38.68, 70.61, -80.13]}
            rotation={[-Math.PI / 2, 0, -0.27]}
            scale={3.14}
          >
            <mesh
              geometry={nodes.Cube018_Material013_0.geometry}
              material={materials["Material.013"]}
            />
            <mesh
              geometry={nodes.Cube018_Material_0.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Cube018_Red_0.geometry}
              material={materials.material}
            />
          </group>
          <group
            position={[29.47, 17.22, -49.4]}
            rotation={[-Math.PI / 2, 0, 2.72]}
            scale={[0.77, 0.77, 1.91]}
          >
            <mesh
              geometry={nodes.Cylinder023_Silver_0.geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Cylinder023_Red_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Cylinder023_Material007_0.geometry}
              material={materials.White}
            />
            <mesh
              geometry={nodes.Cylinder023_Material_0.geometry}
              material={materials.Material}
            />
          </group>

          <mesh
            geometry={nodes.Cube_Material028_0.geometry}
            material={materials["Material.028"]}
            position={[0, 100, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.Cylinder006_Red_0.geometry}
            material={materials.material}
            position={[14.92, 71.35, -79.29]}
            rotation={[-Math.PI / 2, 0, 0.23]}
            scale={2.84}
          />
          <mesh
            geometry={nodes.Cylinder007_Yellow_0.geometry}
            material={materials.Yellow}
            position={[8.53, 71.35, -76.02]}
            rotation={[-Math.PI / 2, 0, 1.41]}
            scale={2.84}
          />
          <mesh
            geometry={nodes.Cube014_Checker_0.geometry}
            material={materials.White}
            position={[-37.1, 32.78, -32.34]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[18.53, 15.9, 15.9]}
          />
          <mesh
            geometry={nodes.Cube013_Checker_0.geometry}
            material={materials.White}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />

          {hideGroup && (
            <mesh
              geometry={nodes.Plane001_Material021_0.geometry}
              material={materials["Material.021"]}
              position={[76.43, 51.52, -31.73]}
              rotation={[Math.PI / 2, 0, -0.5]}
              scale={8.22}
            />
          )}
          {hideGroup && (
            <mesh
              geometry={nodes.Plane003_Material021_0.geometry}
              material={materials["Material.021"]}
              position={[67.62, 51.33, -20.81]}
              rotation={[Math.PI / 2, 0, -0.89]}
              scale={7.37}
            />
          )}
          {hideGroup && (
            <mesh
              geometry={nodes.Plane005_Material021_0.geometry}
              material={materials["Material.021"]}
              position={[37.23, 50.15, 76.99]}
              rotation={[Math.PI / 2, 0, -0.5]}
              scale={8.22}
            />
          )}
          <mesh
            geometry={nodes.Plane006_Material029_0.geometry}
            material={materials["Material.029"]}
            position={[-32.26, 68.16, 15.05]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[11.08, 11.08, 8.96]}
          />
          <mesh
            geometry={nodes.Circle002_Glass002_0.geometry}
            material={materials["Glass.002"]}
            position={[-85.91, 75.47, 39.25]}
            rotation={[-Math.PI / 2, 0, 1.3]}
            scale={2.18}
          />
          <mesh
            geometry={nodes.Cube015_Red_0.geometry}
            material={materials.material}
            position={[-77.94, 90.16, -64.65]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={7.6}
          />
          <mesh
            geometry={nodes.Circle008_Material030_0.geometry}
            material={materials["Material.030"]}
            position={[-79.63, 90.96, -65.08]}
            rotation={[-Math.PI / 2, 0, -1.09]}
            scale={5.18}
          />
          <mesh
            geometry={nodes.Cylinder013_White_0.geometry}
            material={materials.White}
            position={[-79.19, 75.97, -70.01]}
            rotation={[-Math.PI / 2, 0, 1.01]}
            scale={4.2}
          />
          <mesh
            geometry={nodes.Cylinder014_White_0.geometry}
            material={materials.White}
            position={[-79.19, 76.57, -70.31]}
            rotation={[-Math.PI / 2, 0, 1.36]}
            scale={4.2}
          />
          <mesh
            geometry={nodes.Cylinder015_White_0.geometry}
            material={materials.White}
            position={[-79.33, 77.15, -70.1]}
            rotation={[-Math.PI / 2, 0, -0.16]}
            scale={4.2}
          />
          <mesh
            geometry={nodes.Cylinder016_White_0.geometry}
            material={materials.White}
            position={[-79.06, 77.75, -70.22]}
            rotation={[-Math.PI / 2, 0, 0.19]}
            scale={4.2}
          />
          <mesh
            geometry={nodes.Cylinder017_White_0.geometry}
            material={materials.White}
            position={[-79.54, 78.28, -69.81]}
            rotation={[-Math.PI / 2, 0, -0.16]}
            scale={4.2}
          />
          <mesh
            geometry={nodes.Cylinder018_White_0.geometry}
            material={materials.White}
            position={[-79.26, 78.88, -69.92]}
            rotation={[-Math.PI / 2, 0, 0.19]}
            scale={4.2}
          />
          <mesh
            geometry={nodes.Cylinder019_White_0.geometry}
            material={materials.White}
            position={[-79.54, 79.42, -69.81]}
            rotation={[-Math.PI / 2, 0, -0.16]}
            scale={4.2}
          />
          <mesh
            geometry={nodes.Cylinder020_White_0.geometry}
            material={materials.White}
            position={[-79.26, 80.01, -69.58]}
            rotation={[-1.46, 0, 0.19]}
            scale={4.2}
          />
          <mesh
            geometry={nodes.Cube016_Red_0.geometry}
            material={materials.material}
            position={[-77.94, 94.19, -0.65]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[7.6, 7.6, 10.43]}
          />
          <mesh
            geometry={nodes.Circle012_Glass001_0.geometry}
            material={materials["Glass.001"]}
            position={[-79.88, 74.37, -4.69]}
            rotation={[Math.PI / 2, 0, 2.83]}
            scale={[-4.1, 4.1, 3.26]}
          />
          <mesh
            geometry={nodes.Circle013_Glass001_0.geometry}
            material={materials["Glass.001"]}
            position={[-80.44, 74.37, 3.14]}
            rotation={[Math.PI / 2, 0, 2.83]}
            scale={[-4.1, 4.1, 3.26]}
          />
          <mesh
            geometry={nodes.Circle014_Glass001_0.geometry}
            material={materials["Glass.001"]}
            position={[-79.88, 80.32, -4.69]}
            rotation={[Math.PI / 2, 0, 2.83]}
            scale={[-3.91, 3.91, 3.11]}
          />
          <mesh
            geometry={nodes.Circle015_Glass001_0.geometry}
            material={materials["Glass.001"]}
            position={[-80.79, 80.32, 3]}
            rotation={[Math.PI / 2, 0, 2.83]}
            scale={[-3.91, 3.91, 3.11]}
          />
          {hideGroup && (
            <mesh
              geometry={nodes.Plane008_Material021_0.geometry}
              material={materials["Material.021"]}
              position={[-35.29, 70.05, -11.92]}
              rotation={[Math.PI / 2, 0, 2.51]}
              scale={8.22}
            />
          )}
          {hideGroup && (
            <mesh
              geometry={nodes.Plane009_Material021_0.geometry}
              material={materials["Material.021"]}
              position={[-27.93, 69.48, -21.28]}
              rotation={[Math.PI / 2, 0, 2.12]}
              scale={7.37}
            />
          )}
          <mesh
            geometry={nodes.Circle004_Material030_0.geometry}
            material={materials["Material.030"]}
            position={[-79.63, 98.15, -4.57]}
            rotation={[-Math.PI / 2, 0, -1.66]}
            scale={3.92}
          />

          <mesh
            geometry={nodes.Circle005_Material030_0.geometry}
            material={materials["Material.030"]}
            position={[-80.27, 95.21, 4]}
            rotation={[-Math.PI / 2, 0, -1.66]}
            scale={3.92}
          />
          <mesh
            geometry={nodes.Cylinder022__0.geometry}
            material={materials["Cylinder.022__0"]}
            position={[-1.36, 71.35, -78.73]}
            rotation={[-Math.PI / 2, 0, 0.56]}
            scale={2.84}
          />
          <mesh
            geometry={nodes.Circle006_Material013_0.geometry}
            material={materials["Material.013"]}
            position={[-25.1, 68.38, -81.02]}
            rotation={[-Math.PI / 2, 0, 0.86]}
            scale={2.9}
          />
        </group>
      </group>
    </Canvas>
  );
}

useGLTF.preload("./assets/resto/scene-transformed.glb");
