/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Joe McDowall (https://sketchfab.com/joboto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-doggy-1c8c763518ab4751bfcddf0b6a34011a
Title: Low poly doggy
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Doggo(props) {
  const { nodes, materials } = useGLTF("./assets/doggo/scene-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cylinder001_0.geometry}
          material={materials["Shiba-inu"]}
          position={[0, 0.87, 4.73]}
        />
        <mesh
          geometry={nodes.Plane_0.geometry}
          material={materials["Shiba-inu"]}
          position={[0, 5.18, 6.64]}
          scale={[0.27, 0.66, 0.66]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./assets/doggo/scene-transformed.glb");
