/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Daniele Cocchi (https://sketchfab.com/Cocchi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/80s-hacker-boy-room-low-poly-50519527cfa04f5db1e765a52567b527
Title: 80s Hacker Boy Room - Low Poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function HackerRoom(props) {
  const { nodes, materials } = useGLTF(
    "./assets/hackerRoom/scene-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group position={[-33.9, -6.9, -20.3]} rotation={[-1.33, 0, -0.82]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, 0.15, -46.87]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[38, 1.5, 38]}
          >
            <mesh
              geometry={nodes.pCube1_lambert2_0.geometry}
              material={materials.lambert2}
            />
            <mesh
              geometry={nodes.pCube1_lambert3_0.geometry}
              material={materials.lambert3}
            />
          </group>
          <group
            position={[-12.48, 11.74, -47.77]}
            rotation={[0, 0.3, 0]}
            scale={[3.51, 3.51, 4.01]}
          >
            <mesh
              geometry={nodes.pCube10_lambert18_0.geometry}
              material={materials.lambert18}
            />
            <mesh
              geometry={nodes.pCube10_lambert20_0.geometry}
              material={materials.lambert20}
            />
            <mesh
              geometry={nodes.pCube10_lambert19_0.geometry}
              material={materials.lambert19}
            />
          </group>
          <group
            position={[-14.01, 10.63, -41.87]}
            scale={[10.98, 19.56, 0.72]}
          >
            <mesh
              geometry={nodes.pCube11_lambert10_0.geometry}
              material={materials.lambert10}
            />
            <mesh
              geometry={nodes.pCube11_blinn2_0.geometry}
              material={materials.blinn2}
            />
            <mesh
              geometry={nodes.pCube11_lambert1_0.geometry}
              material={materials.lambert1}
            />
            <mesh
              geometry={nodes.pCube11_blinn3_0.geometry}
              material={materials.blinn3}
            />
            <mesh
              geometry={nodes.pCube11_lambert21_0.geometry}
              material={materials.lambert21}
            />
            <mesh
              geometry={nodes.pCube11_lambert30_0.geometry}
              material={materials.lambert30}
            />
            <mesh
              geometry={nodes.pCube11_blinn10_0.geometry}
              material={materials.blinn10}
            />
          </group>
          <group position={[-3.13, 9.98, -60.58]} scale={[6.02, 1.27, 4.19]}>
            <mesh
              geometry={nodes.pCube12_lambert13_0.geometry}
              material={materials.lambert13}
            />
            <mesh
              geometry={nodes.pCube12_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[-12.18, 10.16, -59.11]}
            rotation={[0, Math.PI / 4, 0]}
            scale={[7.07, 1.6, 5.75]}
          >
            <mesh
              geometry={nodes.pCube13_lambert14_0.geometry}
              material={materials.lambert13}
            />
            <mesh
              geometry={nodes.pCube13_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[-13.44, 14.51, -60.22]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={[6.99, 5.38, 6.4]}
          >
            <mesh
              geometry={nodes.pCube14_lambert24_0.geometry}
              material={materials.lambert18}
            />
            <mesh
              geometry={nodes.pCube14_lambert25_0.geometry}
              material={materials.lambert25}
            />
          </group>
          <group
            position={[-3.18, 13.41, -61.47]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[5.24, 4.26, 4.72]}
          >
            <mesh
              geometry={nodes.pCube15_lambert26_0.geometry}
              material={materials.lambert26}
            />
            <mesh
              geometry={nodes.pCube15_lambert28_0.geometry}
              material={materials.lambert28}
            />
          </group>
          <group
            position={[4.4, 11.17, -59.66]}
            rotation={[0, -Math.PI / 6, 0]}
            scale={[6.24, 3.7, 3.82]}
          >
            <mesh
              geometry={nodes.pCube16_lambert17_0.geometry}
              material={materials.lambert17}
            />
            <mesh
              geometry={nodes.pCube16_lambert12_0.geometry}
              material={materials.lambert12}
            />
          </group>
          <group
            position={[-9.11, 9.53, -54.77]}
            rotation={[0, 0.54, 0]}
            scale={[7.53, 0.28, 2.36]}
          >
            <mesh
              geometry={nodes.pCube17_lambert15_0.geometry}
              material={materials.lambert18}
            />
            <mesh
              geometry={nodes.pCube17_lambert16_0.geometry}
              material={materials.lambert16}
            />
          </group>
          <group position={[-0.9, 18.58, -63.77]} scale={[10.28, 13.95, 0.25]}>
            <mesh
              geometry={nodes.pCube20_lambert8_0.geometry}
              material={materials.lambert8}
            />
            <mesh
              geometry={nodes.pCube20_lambert7_0.geometry}
              material={materials.lambert13}
            />
          </group>
          <group
            position={[12.01, 18.77, -63.77]}
            rotation={[0, 0, 0.04]}
            scale={[7.52, 11.16, 0.21]}
          >
            <mesh
              geometry={nodes.pCube21_lambert5_0.geometry}
              material={materials.lambert13}
            />
            <mesh
              geometry={nodes.pCube21_lambert6_0.geometry}
              material={materials.lambert6}
            />
          </group>
          <group
            position={[9.22, 13.06, -62.55]}
            rotation={[-Math.PI, 1.56, -1.83]}
            scale={[7.53, 0.28, 2.36]}
          >
            <mesh
              geometry={nodes.pCube25_lambert15_0.geometry}
              material={materials.lambert18}
            />
            <mesh
              geometry={nodes.pCube25_lambert16_0.geometry}
              material={materials.lambert16}
            />
          </group>
          <group
            position={[-13.48, 21.15, -5.26]}
            rotation={[0, -0.59, 0]}
            scale={0.22}
          >
            <group
              position={[-130.22, -2.31, -192.96]}
              rotation={[0, 0, 0.08]}
              scale={[1, 3.26, 3.08]}
            >
              <mesh
                geometry={nodes.clank_0016pCube41_clank_0016blinn3_0.geometry}
                material={materials.clank_0016blinn3}
              />
              <mesh
                geometry={nodes.clank_0016pCube41_clank_0016blinn1_0.geometry}
                material={materials.lambert1}
              />
            </group>
            <group
              position={[-130.73, -11.44, -191.23]}
              rotation={[0, Math.PI / 2, 0]}
              scale={[1.33, 1.24, 2.54]}
            >
              <mesh
                geometry={nodes.clank_0016pSphere3_clank_0016blinn1_0.geometry}
                material={materials.lambert1}
              />
              <mesh
                geometry={nodes.clank_0016pSphere3_clank_0016phong4_0.geometry}
                material={materials.clank_0016blinn3}
              />
            </group>
            <group
              position={[-130.73, -11.44, -194.61]}
              rotation={[0, Math.PI / 2, 0]}
              scale={[1.33, 1.24, 2.54]}
            >
              <mesh
                geometry={nodes.clank_0016pSphere2_clank_0016blinn1_0.geometry}
                material={materials.lambert1}
              />
              <mesh
                geometry={nodes.clank_0016pSphere2_clank_0016phong3_0.geometry}
                material={materials.clank_0016blinn3}
              />
              <mesh
                geometry={nodes.clank_0016pSphere2_clank_0016phong2_0.geometry}
                material={materials.clank_0016blinn3}
              />
            </group>
            <group
              position={[-131.96, 4.47, -193.12]}
              rotation={[Math.PI / 2, Math.PI / 2, 0]}
              scale={[3.23, 2.62, 2.66]}
            >
              <mesh
                geometry={nodes.clank_0016pSphere8_clank_0016blinn1_0.geometry}
                material={materials.lambert1}
              />
              <mesh
                geometry={nodes.clank_0016pSphere8_clank_0016blinn6_0.geometry}
                material={materials.clank_0016blinn3}
              />
            </group>
            <group position={[-131.93, 9.46, -192.99]} scale={0.52}>
              <mesh
                geometry={nodes.clank_0016pSphere6_clank_0016phong1_0.geometry}
                material={materials.clank_0016phong1}
              />
              <mesh
                geometry={nodes.clank_0016pSphere6_clank_0016blinn1_0.geometry}
                material={materials.lambert1}
              />
            </group>
            <group
              position={[-131.93, -1.78, -192.96]}
              rotation={[0, Math.PI / 2, 0]}
              scale={5.13}
            >
              <mesh
                geometry={nodes.clank_0016pCube1_clank_0016blinn1_0.geometry}
                material={materials.lambert1}
              />
              <mesh
                geometry={nodes.clank_0016pCube1_clank_0016blinn4_0.geometry}
                material={materials.clank_0016blinn3}
              />
            </group>
            <mesh
              geometry={nodes.clank_0016pCube35_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.93, -7.49, -195.09]}
              rotation={[-Math.PI / 2, -Math.PI / 3, Math.PI / 2]}
              scale={[0.76, 0.76, 0.82]}
            />
            <mesh
              geometry={nodes.clank_0016pCube42_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-129.58, -1.55, -192.99]}
              rotation={[0, 0, 0.47]}
              scale={[0.07, 0.48, 2.04]}
            />
            <mesh
              geometry={nodes.clank_0016pCube43_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-129.52, -2.29, -192.99]}
              rotation={[0, 0, 0.47]}
              scale={[0.07, 0.48, 2.04]}
            />
            <mesh
              geometry={nodes.clank_0016pCube44_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-129.47, -3, -192.99]}
              rotation={[0, 0, 0.47]}
              scale={[0.07, 0.48, 2.04]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder7_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-131.93, -7.49, -194.69]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.71, 0.58, 0.71]}
            />
            <mesh
              geometry={nodes.clank_0016pCube50_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-134.22, -1.04, -192.98]}
              rotation={[0, 0, -2.94]}
              scale={[0.06, 0.32, 1.29]}
            />
            <mesh
              geometry={nodes.clank_0016pCube49_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-134.24, -1.5, -192.98]}
              rotation={[0, 0, -2.94]}
              scale={[0.06, 0.32, 1.29]}
            />
            <mesh
              geometry={nodes.clank_0016pCube48_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-134.26, -1.96, -192.98]}
              rotation={[0, 0, -2.94]}
              scale={[0.06, 0.32, 1.29]}
            />
            <mesh
              geometry={nodes.clank_0016pCube47_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-133.62, -1.57, -192.97]}
              rotation={[0, 0, 3.05]}
              scale={[0.89, 2.06, 1.95]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder9_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.93, 1.09, -192.99]}
              scale={[0.44, 0.78, 0.44]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder8_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-131.93, -7.49, -191.27]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.71, 0.58, 0.71]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder12_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-131.93, -9.68, -194.53]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.58, 0.87, 0.58]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder4_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-131.93, -5.35, -192.98]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.25, 2.25, 0.25]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder3_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-131.93, 0.75, -192.99]}
              scale={[0.77, 0.35, 0.77]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder10_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-131.93, -5.62, -191.24]}
              scale={[0.42, 0.65, 0.42]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder11_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-131.93, -9.68, -191.33]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.58, 0.87, 0.58]}
            />
            <mesh
              geometry={nodes.clank_0016pCube2_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-127.25, -3.45, -195.95]}
              rotation={[-Math.PI / 2, Math.PI / 6, 1.31]}
              scale={[1.04, 2.57, 2.66]}
            />
            <mesh
              geometry={nodes.clank_0016pCube25_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-129.76, -2, -196.44]}
              rotation={[-Math.PI / 2, -0.26, Math.PI / 2]}
              scale={[0.58, 0.58, 0.63]}
            />
            <mesh
              geometry={nodes.clank_0016pCube28_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.94, -0.74, -196.21]}
              rotation={[Math.PI / 2, -Math.PI / 3, -Math.PI / 2]}
              scale={[1.1, 1.1, 1.19]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder15_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-129.52, -2.14, -196.03]}
              rotation={[0, 0, Math.PI / 3]}
              scale={[0.35, 2.93, 0.35]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder14_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.9, -0.77, -192.98]}
              rotation={[Math.PI / 2, Math.PI / 3, 0]}
              scale={[0.31, 3.18, 0.31]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder1_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-131.93, -0.75, -196.01]}
              rotation={[-Math.PI / 2, -Math.PI / 3, 0]}
              scale={[1.1, 0.49, 1.1]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder6_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-129.75, -2.01, -196.04]}
              rotation={[Math.PI / 2, Math.PI / 3, 0]}
              scale={[0.59, 0.47, 0.59]}
            />
            <mesh
              geometry={nodes.clank_0016pCube54_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.33, -1.71, -194.73]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[0.38, 0.38, 0.41]}
            />
            <mesh
              geometry={nodes.clank_0016pCube53_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-132.59, -1.71, -194.73]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[0.38, 0.38, 0.41]}
            />
            <mesh
              geometry={nodes.clank_0016pCube52_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.33, -1.71, -191.17]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[0.38, 0.38, 0.41]}
            />
            <mesh
              geometry={nodes.clank_0016pCube51_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-132.59, -1.71, -191.17]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[0.38, 0.38, 0.41]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder13_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-131.93, -5.62, -194.69]}
              scale={[0.42, 0.65, 0.42]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder18_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.93, -8.46, -194.67]}
              rotation={[-Math.PI, 0, 0]}
              scale={[0.35, 2.44, 0.35]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder17_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.93, -8.46, -191.24]}
              rotation={[-Math.PI, 0, 0]}
              scale={[0.35, 2.44, 0.35]}
            />
            <mesh
              geometry={nodes.clank_0016pSphere5_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-131.93, -0.76, -191.36]}
              scale={0.52}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder19_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-131.93, 7.09, -192.98]}
              scale={0.46}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder24_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-131.34, 3.85, -192.99]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.82, 2.65, 0.82]}
            />
            <mesh
              geometry={nodes.clank_0016pSphere4_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-131.93, -0.76, -194.57]}
              scale={0.52}
            />
            <mesh
              geometry={nodes.clank_0016pCube36_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.93, -7.49, -194.26]}
              rotation={[Math.PI / 2, -Math.PI / 3, Math.PI / 2]}
              scale={[0.76, 0.76, 0.82]}
            />
            <mesh
              geometry={nodes.clank_0016pSphere10_clank_0016phongE1_0.geometry}
              material={materials.clank_0016phongE1}
              position={[-129.67, 5.2, -193.92]}
              rotation={[-2.25, 1.24, 2.24]}
              scale={[0.79, 0.79, 0.43]}
            />
            <mesh
              geometry={nodes.clank_0016pSphere9_clank_0016phongE1_0.geometry}
              material={materials.clank_0016phongE1}
              position={[-129.73, 5.2, -191.89]}
              rotation={[-0.7, 1.18, 0.74]}
              scale={[0.79, 0.79, 0.43]}
            />
            <mesh
              geometry={nodes.clank_0016pCube3_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-126.5, -0.65, -189.98]}
              rotation={[-Math.PI / 2, 0, 1.83]}
              scale={[1.04, 2.57, 2.66]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder25_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-125.61, 1.37, -190.34]}
              rotation={[-1.72, 0.5, -1.27]}
              scale={[0.07, 0.27, 0.1]}
            />
            <mesh
              geometry={nodes.clank_0016pCube10_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-123.72, -1.27, -190.72]}
              rotation={[-Math.PI / 2, 0, 1.83]}
              scale={[0.53, 0.95, 0.96]}
            />
            <mesh
              geometry={nodes.clank_0016pCube30_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.93, -9.67, -193.83]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
              scale={[0.74, 0.74, 0.79]}
            />
            <mesh
              geometry={nodes.clank_0016pCube31_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.93, -9.67, -190.62]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
              scale={[0.74, 0.74, 0.79]}
            />
            <mesh
              geometry={nodes.clank_0016pCube32_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.93, -9.67, -192.04]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[0.74, 0.74, 0.79]}
            />
            <mesh
              geometry={nodes.clank_0016pCube29_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.93, -9.67, -195.25]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[0.74, 0.74, 0.79]}
            />
            <mesh
              geometry={nodes.clank_0016pCube33_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.32, 3.86, -195.49]}
              rotation={[-Math.PI / 2, Math.PI / 4, Math.PI / 2]}
              scale={[0.65, 0.65, 0.7]}
            />
            <mesh
              geometry={nodes.clank_0016pCube37_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.93, -7.49, -190.86]}
              rotation={[Math.PI / 2, -Math.PI / 3, Math.PI / 2]}
              scale={[0.76, 0.76, 0.82]}
            />
            <mesh
              geometry={nodes.clank_0016pCube38_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.93, -7.49, -191.69]}
              rotation={[-Math.PI / 2, -Math.PI / 3, Math.PI / 2]}
              scale={[0.76, 0.76, 0.82]}
            />
            <mesh
              geometry={nodes.clank_0016pCube34_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.32, 3.86, -190.47]}
              rotation={[Math.PI / 2, Math.PI / 4, Math.PI / 2]}
              scale={[0.65, 0.65, 0.7]}
            />
            <mesh
              geometry={nodes.clank_0016pCube39_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.93, -5.34, -195.19]}
              rotation={[-Math.PI / 2, Math.PI / 4, Math.PI / 2]}
              scale={[0.25, 0.25, 0.27]}
            />
            <mesh
              geometry={nodes.clank_0016pCube40_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.93, -5.34, -190.77]}
              rotation={[Math.PI / 2, Math.PI / 4, Math.PI / 2]}
              scale={[0.25, 0.25, 0.27]}
            />
            <mesh
              geometry={nodes.clank_0016pCube27_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-131.92, -0.65, -189.73]}
              rotation={[Math.PI / 2, Math.PI / 6, Math.PI / 2]}
              scale={[1.1, 1.1, 1.19]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder21_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-125.46, -2.13, -195.68]}
              rotation={[-1.32, 1.02, 1.13]}
              scale={[0.07, 0.27, 0.1]}
            />
            <mesh
              geometry={nodes.clank_0016pCube22_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-127.55, -3.28, -196.43]}
              rotation={[-2.06, -0.99, 1.15]}
              scale={[0.74, 0.74, 0.79]}
            />
            <mesh
              geometry={nodes.clank_0016pCube45_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-125.99, -2.47, -195.79]}
              rotation={[-1.32, 1.02, 1.13]}
              scale={[0.59, 0.83, 1.2]}
            />
            <mesh
              geometry={nodes.clank_0016pCube8_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-125.19, -3.91, -195.44]}
              rotation={[-Math.PI / 2, Math.PI / 6, 1.31]}
              scale={[0.42, 1.99, 0.46]}
            />
            <mesh
              geometry={nodes.clank_0016pCube4_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-125.38, -3.8, -195.5]}
              rotation={[Math.PI / 2, -Math.PI / 6, 1.83]}
              scale={[0.64, 0.91, 1]}
            />
            <mesh
              geometry={nodes.clank_0016pCube46_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-125.14, -1.95, -195.58]}
              rotation={[-1.03, 0.92, 0.89]}
              scale={[0.45, 0.62, 0.61]}
            />
            <mesh
              geometry={nodes.clank_0016pCube7_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-125.14, -5.38, -195.23]}
              rotation={[-Math.PI / 2, Math.PI / 6, 1.31]}
              scale={[0.53, 0.95, 0.96]}
            />
            <mesh
              geometry={nodes.clank_0016pCube9_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-125.82, -5, -195.44]}
              rotation={[-Math.PI / 2, Math.PI / 6, 1.31]}
              scale={[0.42, 1.99, 0.46]}
            />
            <mesh
              geometry={nodes.clank_0016pCube6_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-126.01, -4.89, -195.5]}
              rotation={[Math.PI / 2, -Math.PI / 6, 1.83]}
              scale={[0.64, 0.91, 1]}
            />
            <mesh
              geometry={nodes.clank_0016pCube5_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-124.51, -4.28, -195.23]}
              rotation={[-Math.PI / 2, Math.PI / 6, 1.31]}
              scale={[0.53, 0.95, 0.96]}
            />
            <mesh
              geometry={nodes.clank_0016pCube15_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-124.72, -0.02, -190.45]}
              rotation={[Math.PI / 2, 0, 1.31]}
              scale={[0.64, 0.91, 1]}
            />
            <mesh
              geometry={nodes.clank_0016pCube14_clank_0016blinn5_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-124.5, -1.28, -190.51]}
              rotation={[-Math.PI / 2, 0, 1.83]}
              scale={[0.42, 1.99, 0.46]}
            />
            <mesh
              geometry={nodes.clank_0016pCube13_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-124.5, -0.02, -190.51]}
              rotation={[-Math.PI / 2, 0, 1.83]}
              scale={[0.42, 1.99, 0.46]}
            />
            <mesh
              geometry={nodes.clank_0016pCube11_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-124.72, -1.28, -190.45]}
              rotation={[Math.PI / 2, 0, 1.31]}
              scale={[0.64, 0.91, 1]}
            />
            <mesh
              geometry={nodes.clank_0016pCube12_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-123.72, 0, -190.72]}
              rotation={[-Math.PI / 2, 0, 1.83]}
              scale={[0.53, 0.95, 0.96]}
            />
            <mesh
              geometry={nodes.clank_0016pCube17_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-125.45, 1.7, -190.43]}
              rotation={[-1.92, 0.44, -1.18]}
              scale={[0.45, 0.62, 0.61]}
            />
            <mesh
              geometry={nodes.clank_0016pCube24_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-126.84, -0.65, -189.48]}
              rotation={[0, -1.31, 0]}
              scale={[0.74, 0.74, 0.79]}
            />
            <mesh
              geometry={nodes.clank_0016pCube16_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-125.93, 0.82, -190.22]}
              rotation={[-1.72, 0.5, -1.27]}
              scale={[0.59, 0.83, 1.2]}
            />
            <mesh
              geometry={nodes.clank_0016pCube26_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-129.41, -0.65, -189.49]}
              rotation={[-Math.PI / 2, Math.PI / 4, -Math.PI / 2]}
              scale={[0.58, 0.58, 0.63]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder16_clank_0016blinn2_0.geometry}
              material={materials.clank_0016blinn3}
              position={[-129.12, -0.65, -189.9]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.35, 2.93, 0.35]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder5_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-129.39, -0.65, -189.86]}
              rotation={[Math.PI / 2, Math.PI / 2, 0]}
              scale={[0.59, 0.47, 0.59]}
            />
            <mesh
              geometry={nodes.clank_0016pCylinder2_clank_0016blinn1_0.geometry}
              material={materials.lambert1}
              position={[-131.91, -0.65, -189.93]}
              rotation={[Math.PI / 2, Math.PI / 2, 0]}
              scale={[1.1, 0.49, 1.1]}
            />
          </group>
          <group
            position={[-9.15, 6.31, 15.97]}
            rotation={[0, 0, -0.17]}
            scale={0.06}
          >
            <mesh
              geometry={nodes.pCylinder7_lambert31_0.geometry}
              material={materials.clank_0016phong1}
              position={[-7.73, 69.39, -1005.18]}
              scale={[3.61, 0.6, 3.61]}
            />
            <mesh
              geometry={nodes.pCube27_lambert34_0.geometry}
              material={materials.lambert34}
              position={[0, 67.6, -998.17]}
              scale={[25.99, 2.66, 25.99]}
            />
            <mesh
              geometry={nodes.pSphere1_lambert31_0.geometry}
              material={materials.clank_0016phong1}
              position={[-5.76, 86.88, -993.34]}
              scale={5}
            />
            <mesh
              geometry={nodes.pCylinder8_lambert32_0.geometry}
              material={materials.blinn10}
              position={[3.02, 69.39, -1001.79]}
              scale={[3.61, 0.6, 3.61]}
            />
            <mesh
              geometry={nodes.pCylinder10_lambert35_0.geometry}
              material={materials.lambert18}
              position={[-5.75, 69.39, -993.3]}
              scale={[5.34, 0.88, 5.34]}
            />
            <mesh
              geometry={nodes.pCylinder9_lambert33_0.geometry}
              material={materials.lambert23}
              position={[7.26, 69.39, -991.6]}
              scale={[3.61, 0.6, 3.61]}
            />
          </group>
          <group
            position={[-9.15, 6.31, 19.63]}
            rotation={[0, 0, -0.17]}
            scale={0.06}
          >
            <mesh
              geometry={nodes.pCylinder7_lambert31_0_1.geometry}
              material={materials.clank_0016phong1}
              position={[-7.73, 69.39, -1005.18]}
              scale={[3.61, 0.6, 3.61]}
            />
            <mesh
              geometry={nodes.pCube27_lambert34_0_1.geometry}
              material={materials.lambert34}
              position={[0, 67.6, -998.17]}
              scale={[25.99, 2.66, 25.99]}
            />
            <mesh
              geometry={nodes.pSphere1_lambert31_0_1.geometry}
              material={materials.clank_0016phong1}
              position={[-5.76, 86.88, -993.34]}
              scale={5}
            />
            <mesh
              geometry={nodes.pCylinder8_lambert32_0_1.geometry}
              material={materials.blinn10}
              position={[3.02, 69.39, -1001.79]}
              scale={[3.61, 0.6, 3.61]}
            />
            <mesh
              geometry={nodes.pCylinder10_lambert35_0_1.geometry}
              material={materials.lambert18}
              position={[-5.75, 69.39, -993.3]}
              scale={[5.34, 0.88, 5.34]}
            />
            <mesh
              geometry={nodes.pCylinder9_lambert33_0_1.geometry}
              material={materials.lambert23}
              position={[7.26, 69.39, -991.6]}
              scale={[3.61, 0.6, 3.61]}
            />
          </group>
          <group
            position={[6.53, 8.76, -64.21]}
            rotation={[0, -1, 0.29]}
            scale={0.21}
          >
            <group
              position={[32.93, -3.52, 10.98]}
              rotation={[Math.PI / 2, -0.32, Math.PI / 2]}
              scale={[1.96, 6.41, 3.93]}
            >
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCube2_NMSMultyTool_0010phong4_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong4}
              />
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCube2_NMSMultyTool_0010phong1_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong1}
              />
            </group>
            <group
              position={[32.07, -3.23, 6.54]}
              rotation={[-Math.PI / 2, -1.25, Math.PI / 2]}
              scale={[1.92, 2.79, 1.68]}
            >
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCylinder2_NMSMultyTool_0010phong7_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong7}
              />
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCylinder2_NMSMultyTool_0010phong8_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong8}
              />
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCylinder2_NMSMultyTool_0010phong2_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong4}
              />
            </group>
            <group
              position={[30.8, -2.8, 4.33]}
              rotation={[0, 0, 1.25]}
              scale={[3, 3, 7.07]}
            >
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pSphere1_NMSMultyTool_0010phong2_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong4}
              />
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pSphere1_NMSMultyTool_0010phong5_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong5}
              />
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pSphere1_NMSMultyTool_0010phong6_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong5}
              />
            </group>
            <group
              position={[38.69, -5.45, 6.62]}
              rotation={[0, 0, 1.25]}
              scale={[2.45, 4.72, 2.45]}
            >
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCube1_NMSMultyTool_0010phong1_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong1}
              />
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCube1_NMSMultyTool_0010phong3_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong4}
              />
            </group>
            <group
              position={[33.33, -3.79, -0.26]}
              rotation={[-Math.PI / 2, -1.25, 3.13]}
              scale={[0.86, 1.52, 0.92]}
            >
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCylinder8_NMSMultyTool_0010phong7_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong7}
              />
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCylinder8_NMSMultyTool_0010phong8_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong8}
              />
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCylinder8_NMSMultyTool_0010phong2_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong4}
              />
            </group>
            <group
              position={[33.72, -2.43, 3.37]}
              rotation={[-Math.PI / 2, -1.25, Math.PI / 2]}
              scale={[0.86, 1.52, 0.92]}
            >
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCylinder7_NMSMultyTool_0010phong7_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong7}
              />
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCylinder7_NMSMultyTool_0010phong8_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong8}
              />
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCylinder7_NMSMultyTool_0010phong2_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong4}
              />
            </group>
            <group
              position={[31.31, -2.97, 10.35]}
              rotation={[-Math.PI / 2, -1.25, 0]}
              scale={[1.69, 2.46, 1.4]}
            >
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCylinder3_NMSMultyTool_0010phong1_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong1}
              />
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCylinder3_NMSMultyTool_0010phong9_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong9}
              />
            </group>
            <group
              position={[34.59, -4.08, 10.45]}
              rotation={[-Math.PI / 2, -1.25, 0]}
              scale={[1.05, 1.53, 0.95]}
            >
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCylinder4_NMSMultyTool_0010phong10_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong9}
              />
              <mesh
                geometry={
                  nodes.NMSMultyTool_0010pCylinder4_NMSMultyTool_0010phong1_0
                    .geometry
                }
                material={materials.NMSMultyTool_0010phong1}
              />
            </group>
            <mesh
              geometry={
                nodes.NMSMultyTool_0010pCylinder1_NMSMultyTool_0010phong2_0
                  .geometry
              }
              material={materials.NMSMultyTool_0010phong4}
              position={[37.94, -5.2, 8.5]}
              rotation={[Math.PI, 0, -2.82]}
              scale={[1.06, 2.41, 1.26]}
            />
            <mesh
              geometry={
                nodes.NMSMultyTool_0010pCube3_NMSMultyTool_0010phong2_0.geometry
              }
              material={materials.NMSMultyTool_0010phong4}
              position={[38.06, -5.24, 4.39]}
              rotation={[Math.PI / 2, -0.32, Math.PI / 2]}
              scale={[12.11, 4.62, 3.47]}
            />
            <mesh
              geometry={
                nodes.NMSMultyTool_0010pCylinder5_NMSMultyTool_0010phong1_0
                  .geometry
              }
              material={materials.NMSMultyTool_0010phong1}
              position={[34.48, -0.44, -0.73]}
              rotation={[-1.64, -1.25, -0.07]}
              scale={[0.46, 4.83, 0.46]}
            />
            <mesh
              geometry={
                nodes.NMSMultyTool_0010pSphere3_NMSMultyTool_0010phong1_0
                  .geometry
              }
              material={materials.NMSMultyTool_0010phong1}
              position={[32.65, -3.42, 4.57]}
              rotation={[Math.PI / 2, -0.32, Math.PI / 2]}
              scale={[6.61, 3.91, 2.79]}
            />
            <mesh
              geometry={
                nodes.NMSMultyTool_0010pSphere2_NMSMultyTool_0010phong2_0
                  .geometry
              }
              material={materials.NMSMultyTool_0010phong4}
              position={[34.81, -4.15, 4.33]}
              rotation={[0, 0, -1.89]}
              scale={[3, 3, 7.07]}
            />
          </group>
          <mesh
            geometry={nodes.pCube2_lambert9_0.geometry}
            material={materials.lambert9}
            position={[-12.18, 9, -52.88]}
            scale={[8, 0.74, 19.94]}
          />
          <mesh
            geometry={nodes.pCube3_lambert9_0.geometry}
            material={materials.lambert9}
            position={[-9.45, 5.07, -44.87]}
            scale={[1.22, 8.09, 1.22]}
          />
          <mesh
            geometry={nodes.pCube4_lambert9_0.geometry}
            material={materials.lambert9}
            position={[-15.08, 5.07, -44.87]}
            scale={[1.22, 8.09, 1.22]}
          />
          <mesh
            geometry={nodes.pCube6_lambert9_0.geometry}
            material={materials.lambert9}
            position={[10.55, 5.07, -56.73]}
            scale={[1.22, 8.09, 1.22]}
          />
          <mesh
            geometry={nodes.pCube7_lambert9_0.geometry}
            material={materials.lambert9}
            position={[-5.45, 5.07, -56.73]}
            scale={[1.22, 8.09, 1.22]}
          />
          <mesh
            geometry={nodes.pCube8_lambert9_0.geometry}
            material={materials.lambert9}
            position={[10.55, 5.07, -61.64]}
            scale={[1.22, 8.09, 1.22]}
          />
          <mesh
            geometry={nodes.pCube9_lambert9_0.geometry}
            material={materials.lambert9}
            position={[-5.45, 5.07, -61.64]}
            scale={[1.22, 8.09, 1.22]}
          />
          <mesh
            geometry={nodes.pCylinder1_lambert11_0.geometry}
            material={materials.lambert11}
            position={[-11, 3.52, -48.08]}
            scale={2.63}
          />
          <mesh
            geometry={nodes.pCube18_lambert1_0.geometry}
            material={materials.lambert1}
            position={[-4.14, 9.51, -56.05]}
            rotation={[-Math.PI, -1.31, -Math.PI]}
            scale={[1.33, 0.27, 0.8]}
          />
          <mesh
            geometry={nodes.pCylinder2_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-15.55, 23.94, -46.51]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.36, 17.59, 1.36]}
          />
          <mesh
            geometry={nodes.pCylinder3_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-15.55, 11.97, -62.31]}
            rotation={[-Math.PI, 0, 0]}
            scale={[1.36, 11.86, 1.36]}
          />
          <mesh
            geometry={nodes.pCube19_lambert4_0.geometry}
            material={materials.lambert4}
            position={[8.38, 4.55, -35]}
            rotation={[-Math.PI, -0.14, -Math.PI]}
            scale={[21.46, 9.63, 8.85]}
          />
          <mesh
            geometry={nodes.pCube22_lambert22_0.geometry}
            material={materials.lambert22}
            position={[-16.84, 19.35, -45.11]}
            rotation={[-Math.PI / 2, 1.53, 1.67]}
            scale={[2.61, 3.87, 0.07]}
          />
          <mesh
            geometry={nodes.pCube23_lambert23_0.geometry}
            material={materials.lambert23}
            position={[-16.84, 18.31, -46.93]}
            rotation={[-Math.PI / 2, 1.53, 1.39]}
            scale={[2.61, 3.87, 0.07]}
          />
          <mesh
            geometry={nodes.pCylinder4_blinn5_0.geometry}
            material={materials.blinn5}
            position={[0.45, 9.4, -56.62]}
            rotation={[0, -0.08, 0]}
            scale={[0.9, 0.03, 0.9]}
          />
          <mesh
            geometry={nodes.pCylinder5_blinn4_0.geometry}
            material={materials.lambert22}
            position={[-13.96, 13.94, -52.18]}
            rotation={[0.06, -0.01, 0.23]}
            scale={[1, 1.41, 1]}
          />
          <mesh
            geometry={nodes.pCube24_lambert1_0.geometry}
            material={materials.lambert1}
            position={[-16.56, 14.06, -52.16]}
            rotation={[0, 0, -1.19]}
            scale={[0.32, 4.34, 0.32]}
          />
          <mesh
            geometry={nodes.pCylinder6_blinn4_0.geometry}
            material={materials.lambert22}
            position={[-14.87, 9.51, -52.14]}
            rotation={[Math.PI, 0.08, 0]}
            scale={[0.9, 0.03, 0.9]}
          />
          <mesh
            geometry={nodes.pCube26_lambert29_0.geometry}
            material={materials.lambert29}
            position={[-14.85, 18.3, -54.92]}
            scale={[4.47, 0.58, 11.13]}
          />
          <mesh
            geometry={nodes.pCube28_blinn8_0.geometry}
            material={materials.blinn8}
            position={[-15.4, 20.39, -50.58]}
            scale={[2.6, 3.58, 0.7]}
          />
          <mesh
            geometry={nodes.pCube29_blinn8_0.geometry}
            material={materials.blinn8}
            position={[-15.4, 19.89, -51.22]}
            scale={[1.86, 2.56, 0.5]}
          />
          <mesh
            geometry={nodes.pCube30_blinn6_0.geometry}
            material={materials.clank_0016phong1}
            position={[-15.4, 19.89, -51.78]}
            scale={[1.86, 2.56, 0.5]}
          />
          <mesh
            geometry={nodes.pCube31_blinn7_0.geometry}
            material={materials.blinn1}
            position={[-15.4, 20.39, -52.48]}
            scale={[2.6, 3.58, 0.7]}
          />
          <mesh
            geometry={nodes.pCube32_blinn6_0.geometry}
            material={materials.clank_0016phong1}
            position={[-15.4, 20.39, -53.18]}
            scale={[2.6, 3.58, 0.54]}
          />
          <mesh
            geometry={nodes.pCube33_blinn7_0.geometry}
            material={materials.blinn1}
            position={[-15.4, 20.03, -53.86]}
            scale={[2.6, 2.86, 0.54]}
          />
          <mesh
            geometry={nodes.pCube34_blinn7_0.geometry}
            material={materials.blinn1}
            position={[-15.4, 19.89, -54.43]}
            scale={[1.86, 2.56, 0.5]}
          />
          <mesh
            geometry={nodes.pCube35_blinn6_0.geometry}
            material={materials.clank_0016phong1}
            position={[-1.3, 9.93, -58.49]}
            scale={[0.58, 0.64, 0.12]}
          />
          <mesh
            geometry={nodes.pCube36_blinn6_0.geometry}
            material={materials.clank_0016phong1}
            position={[-9.23, 10.2, -58.01]}
            rotation={[0, 0.79, 0]}
            scale={[0.58, 0.64, 0.12]}
          />
          <mesh
            geometry={nodes.pCube37_blinn6_0.geometry}
            material={materials.clank_0016phong1}
            position={[-8.48, 10.2, -58.77]}
            rotation={[0, 0.79, 0]}
            scale={[0.58, 0.64, 0.12]}
          />
          <mesh
            geometry={nodes.pCylinder11_blinn9_0.geometry}
            material={materials.lambert18}
            position={[18.6, 13.67, -63.26]}
            rotation={[-Math.PI, 0, 0]}
            scale={[0.5, 13.91, 0.5]}
          />
          <mesh
            geometry={nodes.pCylinder12_blinn9_0.geometry}
            material={materials.lambert18}
            position={[20.34, 13.67, -63.26]}
            rotation={[-Math.PI, 0, 0]}
            scale={[0.5, 13.91, 0.5]}
          />
          <mesh
            geometry={nodes.pCube38_lambert36_0.geometry}
            material={materials.lambert36}
            position={[0.46, 9.5, -56.55]}
            rotation={[0, 0.49, 0]}
            scale={[2.31, 0.08, 1.51]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./assets/hackerRoom/scene-transformed.glb");
