/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: micaelsampaio (https://sketchfab.com/micaelsampaio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-little-girl-30e234683aa343798c50438af550d863
Title: Low Poly Little Girl
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Person(props) {
  const { nodes, materials } = useGLTF("./assets/person/scene-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.hair} />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./assets/person/scene-transformed.glb");
